version: 2
jobs:
  build:
    docker:
    - image: halu5071/edwards-doc:1.8

    steps:
    - checkout

    - run:
        name: Set up
        command: |
          chmod u+x setup.sh
          ./setup.sh

    - run:
        name: Google Test
        command: |
          chmod u+x run_test.sh
          ./run_test.sh
    - store_test_results:
        path: /cmake-build
    - store_artifacts:
        path: /cmake-build/libpoint.so
        destination: artifact-file